### ISSUE TITLE
I have a issue about running decoder

### ISSUE THREAD

**Issue by hieunguyenquoc** [vietai/SAT#3]
Data loss: Unable to open table file /content/drive/MyDrive/SAT/checkpoint: Failed precondition: /content/drive/MyDrive/SAT/checkpoint; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?

I used a pretrain model : model.augmented.envi.ckpt-1415000.data-00000-of-00001, model.augmented.envi.ckpt-1415000.index,  model.augmented.envi.ckpt-1415000.meta. All 3 file are put in checkpoint

Could somebody help me with this issue ?

**Comment by thtrieu** [comment]
Hi! You might need to pass the option

`--checkpoint_path=$ckpt_path` 

To your command, where `$ckpt_path` is the exact path to the checkpoint you want.

Thank you for brining this to our attention, we'll fix the documentation right away.

**Comment by hieunguyenquoc** [comment]
> Hi! You might need to pass the option
> 
> `--checkpoint_path=$ckpt_path`
> 
> To your command, where `$ckpt_path` is the exact path to the checkpoint you want.
> 
> Thank you for brining this to our attention, we'll fix the documentation right away.

**Comment by hieunguyenquoc** [comment]
First of all, thank you for replying me. But when I check the pretrained model provided in the code : https://console.cloud.google.com/storage/browser/vietai_public/best_vi_translation;tab=objects?prefix=&forceOnObjectsSortingFiltering=false; I don't see a checkpoint file. Then I run the script :
**!python /content/drive/MyDrive/SAT/t2t_decoder.py \
--data_dir=/content/drive/MyDrive/SAT/data \
--problem=translate_envi_iwslt32k \
--hparams_set="transformer_tall9" \
--model=transformer \
--decode_hparams="beam_size=4,alpha=0.6"  \
--decode_from_file=/content/drive/MyDrive/SAT/tmp/tst2012.en \
--decode_to_file=/content/drive/MyDrive/SAT/tmp/tst2012_en2vi.txt  \
--output_dir=/content/drive/MyDrive/SAT/model/eval \
--checkpoint_path=/content/drive/MyDrive/SAT/model/eval/checkpoint**
Because it isn't have a checkpoint file, so it come to this error :
**(0) Data loss: Unable to open table file /content/drive/MyDrive/SAT/model/eval/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[{{node save/RestoreV2_1}}]]
	 [[save/RestoreV2_1/_55]]
  (1) Data loss: Unable to open table file /content/drive/MyDrive/SAT/model/eval/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[{{node save/RestoreV2_1}}]]**
Could you help me with this error ?
PS : The model is in eval file, vocab and tf_records are in data file

**Comment by hotanhoang** [comment]
I had met the same error. 
This is my command: 'python t2t_decoder.py --data_dir=VietAI --problem='translate_class11_appendtag_envi_iwslt32k'  --model=transformer --output_dir='VietAI' --checkpoint_path=/home/hduser/Desktop/SAT/VietAI/model.augmented.envi.ckpt-1415000 --decode_from_file=VietAI/tst2013.en --decode_to_file=VietAI/tst2013_en2vi.txt --hparams_set="transformer_tall9"


Traceback (most recent call last):
  File "t2t_decoder.py", line 35, in <module>
    FLAGS.checkpoint_path or FLAGS.output_dir)
  File "/home/hduser/Desktop/SAT/decoding.py", line 406, in t2t_decoder
    checkpoint_path=checkpoint_path)
  File "/home/hduser/Desktop/SAT/decoding.py", line 306, in decode_from_file_fn
    for elapsed_time, result in timer(result_iter):
  File "/home/hduser/Desktop/SAT/decoding.py", line 300, in timer
    item = next(gen)
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 629, in predict
    hooks=all_hooks) as mon_sess:
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1039, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 750, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1232, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1237, in _create_session
    return self._sess_creator.create_session()
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 903, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 661, in create_session
    self._scaffold.finalize()
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 233, in finalize
    summary.merge_all)
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 298, in get_or_default
    op = default_constructor()
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/summary/summary.py", line 406, in merge_all
    return merge(summary_ops, name=name)
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/summary/summary.py", line 370, in merge
    with _ops.name_scope(name, 'Merge', inputs):
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6530, in __enter__
    g_from_inputs = _get_graph_from_inputs(self._values)
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6165, in _get_graph_from_inputs
    _assert_same_graph(original_graph_element, graph_element)
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6100, in _assert_same_graph
    (item, original_item, graph, original_graph))

**Comment by hieunguyenquoc** [comment]
@hotanhoang
_!python /content/drive/MyDrive/SAT/t2t_decoder.py \
--data_dir=/content/drive/MyDrive/SAT/data \
--problem=translate_envi_iwslt32k \
--hparams_set="transformer_tall9" \
--model=transformer \
--decode_hparams="beam_size=4,alpha=0.6"  \
--decode_from_file=/content/drive/MyDrive/SAT/tmp/tst2012.en \
--decode_to_file=/content/drive/MyDrive/SAT/tmp/tst2012_en2vi.txt  \
--output_dir=/content/drive/MyDrive/SAT/model/eval \
--checkpoint_path=/content/drive/MyDrive/SAT/model/eval/model.augmented.envi.ckpt_
Here is my code

First you need to change the checkpoint name :
model.augmented.envi.ckpt-1415000.data-00000-of-00001
model.augmented.envi.ckpt-1415000.index
model.augmented.envi.ckpt-1415000.meta 
to
model.augmented.envi.ckpt.data-00000-of-00001
model.augmented.envi.ckpt.index
model.augmented.envi.ckpt.meta 

And second, you will need to add the option _checkpoint_path_ like me
This work for me

**Comment by hotanhoang** [comment]
thank you for replying me. But after I changed the checkpoint's name and added the option checkpoint_path like you, it still had the error. It says error in checkpoint_path because It cannot read the pretrain file. 
This is the my code:
python /home/hduser/Desktop/SAT/t2t_decoder.py '
          '--data_dir=/home/hduser/Desktop/SAT/data '
          '--problem=translate_envi_iwslt32k '
          '--hparams_set="transformer_tall9" '
          '--model=transformer '
          '--decode_hparams="beam_size=4,alpha=0.6" '
          '--decode_from_file=/home/hduser/Desktop/SAT/tmp/tst2012.en '
          '--decode_to_file=/home/hduser/Desktop/SAT/tmp/tst2012_en2vi.txt '
          '--output_dir=/home/hduser/Desktop/SAT/model/eval '
          '--checkpoint_path=/home/hduser/Desktop/SAT/model/eval/model.augmented.envi.ckpt

And this is the error:
Traceback (most recent call last):
  File "/home/hduser/Desktop/SAT/t2t_decoder.py", line 35, in <module>
    FLAGS.checkpoint_path or FLAGS.output_dir)
  File "/home/hduser/Desktop/SAT/decoding.py", line 400, in t2t_decoder
    checkpoint_path=checkpoint_path)
  File "/home/hduser/Desktop/SAT/decoding.py", line 300, in decode_from_file_fn
    for elapsed_time, result in timer(result_iter):
  File "/home/hduser/Desktop/SAT/decoding.py", line 294, in timer
    item = next(gen)
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 629, in predict
    hooks=all_hooks) as mon_sess:
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1039, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 750, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1232, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1237, in _create_session
    return self._sess_creator.create_session()
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 903, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 661, in create_session
    self._scaffold.finalize()
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 233, in finalize
    summary.merge_all)
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 298, in get_or_default
    op = default_constructor()
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/summary/summary.py", line 406, in merge_all
    return merge(summary_ops, name=name)
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/summary/summary.py", line 370, in merge
    with _ops.name_scope(name, 'Merge', inputs):
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6530, in __enter__
    g_from_inputs = _get_graph_from_inputs(self._values)
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6165, in _get_graph_from_inputs
    _assert_same_graph(original_graph_element, graph_element)
  File "/home/hduser/Desktop/SAT/env/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6100, in _assert_same_graph
    (item, original_item, graph, original_graph))
ValueError: Tensor("body/parallel_0/body/decoder/layer_0/self_attention/multihead_attention/dot_product_attention/attention:0", shape=(), dtype=string, device=/device:GPU:0) must be from the same graph as Tensor("transformer_hparams:0", shape=(), dtype=string) (graphs are FuncGraph(name=transformer_while_body_6026, id=140363452529872) and <tensorflow.python.framework.ops.Graph object at 0x7fa8ebf93650>).

@hieunguyenquoc Could you help me with this error ?
